### ISSUE TITLE
Customizing Phobos actor name without using PhobosActorName attribute

### ISSUE THREAD

**Issue by object** [petabridge/phobos-issues#81]
I am afraid the PhobosActorName attribute won't help F# developers because it is applied on the actor class level, and both official F# API and Akkling create actors without defining classes: the actors are based on functions. Here's an example from an official Akka F# API:

```
let aref =
    spawn system "my-actor"
        (fun mailbox ->
            let rec loop() = actor {
                let! message = mailbox.Receive()
                // handle an incoming message
                return! loop()
            }
            loop())

```

The mailbox in this example belongs to an instance of an internal class FunActor shared by different actors, and they will still get the same Phobos name.

But can the name be customized by making possible via **IPhobosActorContext** available from **mailbox.UntypedContext.GetInstrumentation()**? The **IPhobosActorContext** has properties **Monitor** and **Tracer**. We are actively using **Tracer** to manage tracing, for example to start a new span (**tracer.StartActiveSpan**). **Monitor** property can be accessed to get the name of the underlying meter (**monitor.Name**). Is this the same name that can be customized using **PhobosActorName** attribute? If so, can the **Meter** class be extended with a name setter method, e.g. **SetName** which will apply it to the current instance of the meter?

_Originally posted by @object in https://github.com/petabridge/phobos-issues/issues/80#issuecomment-2527971723_

**Comment by Arkatufus** [comment]
@object This is from @Aaronontheweb in Discord.

I’ll ask @Arkatufus to implement a version of this that accepts the type name as a ‘PhobosProps’ configuration argument instead of a type annotation

**Comment by Arkatufus** [comment]
@object can you test v2.6.1? I think we fixed it this time, there's an F# sample on how to do it in the release notes.

**Comment by object** [comment]
Will test it in a couple of days.

**Comment by object** [comment]
My first impression that it didn't help, neither to C# or F# actors. I still see in Phobos metrics dashboard FunPersistentActor and FunActor, but I also see PersistentSupervisor actor although it's an actor implemented in C# and I tried to override its type name as well. I till investigate more.

**Comment by Aaronontheweb** [comment]
@object I'm back in the office today and @Arkatufus and I will do some work on our end too

**Comment by Aaronontheweb** [comment]
@object I think I've found your issue - are you using any Phobos HOCON to customize your actor's deployments by any chance, like disabling automatic span creation? It looks like we have a conflict when there's multiple configuration sources involved (was able to reproduce that on our end just now) and the stuff that's added via `Props` loses to the HOCON (which doesn't contain a definition for `ActorTypeName` right now, but we could add one.)

Let us know if that's the case and we'll start getting a fix prepared - otherwise, could you show us some of the `Props` / HOCON you've been using for these actors that aren't using the new custom type name? That would be very helpful!

**Comment by object** [comment]
@Aaronontheweb we are using both HOCON and Akka.Hosting at the moment, because we have a mixture of legacy services (that use HOCON) and new services (that use Akka.Hosting). The new ones have the following code:

```
builder
  .VerboseTracing(false)
  .SetCreateTraceUponReceive(false)
  .IncludeMessagesAlreadyInTrace(true)
  .SetAppendLogsToTrace(true)
  .SetTraceAsk(false)

```

New services also use AddHocon method to configure stuff that not yet can be congurured HOCON-less. So to answer your question: we do both, in different service, and if your hypothesis is correct, we should be able to see overridden actor type names at least in newer services that are configured using Akka.Hosting builder. But apparently this doesn't happen - none of persistent actors have its name customized, it's still FunPersistentActor in all services.

**Comment by Aaronontheweb** [comment]
> New services also use AddHocon method to configure stuff that not yet can be congurured HOCON-less. 

Are you using any HOCON in the `akka.actor.deployment` namespace by chance? That's where I've been able to 100% confirm config issues with this new feature so far. I'll take a look at your programmatic config you've provided here and see if there are any issues with that too.

**Comment by Aaronontheweb** [comment]
cc @object

**Comment by object** [comment]
Yes, we are using yes we use HOCON in deployment section because there was no Akka.Hosting alternative.

**Comment by Aaronontheweb** [comment]
Perfect - that's all I needed to know. I think we'll be able to get that fixed this week.

**Comment by Aaronontheweb** [comment]
This has been fixed in Phobos 2.6.2: https://sdkbin.com/publisher/petabridge/product/phobos/packages/phobos.actor/versions/2.6.2

Release notes with details: https://phobos.petabridge.com/articles/releases/RELEASE_NOTES.html

give that a try and let us know if the issue persists - I tested it pretty thoroughly with different combinations of HOCON / not HOCON and it all works.
